from pathlib import Path
from html import escape

ROOT=Path(__file__).parent
WA='https://wa.me/5519996524100?text='
MAP='https://www.google.com/maps/dir/?api=1&destination=-22.9201181%2C-47.111243'
REVIEWS='https://www.google.com/maps/place/Outlet+do+Maic%C3%A3o+estofados/@-22.9201181,-47.1138179,17z/data=!4m8!3m7!1s0x94c8c93dcca0d9c9:0x56b6540f0e5c46d!8m2!3d-22.9201181!4d-47.111243!9m1!1b1!16s%2Fg%2F11yhg1jf9j'
MAP_EMBED='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3674.8170448754936!2d-47.113817924689336!3d-22.92011807924574!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c8c93dcca0d9c9%3A0x56b6540f0e5c46d!2sOutlet%20do%20Maic%C3%A3o%20estofados!5e0!3m2!1spt-BR!2suk!4v1790688315286!5m2!1spt-BR!2suk'
from urllib.parse import quote

def zap(message): return WA+quote(message)
def button(label,url,kind='primary'): return f'<a class="button {kind}" href="{url}"'+(' target="_blank" rel="noopener"' if url.startswith('http') else '')+f'>{label} </a>'
def header(current):
    links=[('Início','index.html'),('Saldão','saldao.html'),('Comfort','comfort.html'),('Premium','premium.html'),('Visite a loja','index.html#visite')]
    nav=''.join(f'<a class="{"active" if current==name else ""}" href="{url}">{name}</a>' for name,url in links)
    mobile_nav=''.join(f'<a class="{"active" if current==name else ""}" href="{url}" onclick="this.closest(\'details\').open=false">{name}</a>' for name,url in links)
    return f'''<div class="announcement">Loja 02 em Campinas <span>•</span> Encontre seu sofá com a nossa equipe</div><header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="Outlet do Maicão, início"><img src="assets/logo-nova.jpg" alt="" width="50" height="50"><span>OUTLET <small>DO MAICÃO</small></span></a><nav class="desktop-nav" aria-label="Navegação principal">{nav}</nav><details class="mobile-menu"><summary aria-label="Menu de navegação"><span class="menu-bars" aria-hidden="true"><i></i><i></i><i></i></span></summary><nav aria-label="Navegação no celular">{mobile_nav}</nav></details>{button('Falar com a loja',zap('Olá! Vim pelo site e quero ajuda para escolher um sofá.'),'header-button')}</div></header>'''
def footer():
    return f'''<footer class="footer"><div class="container footer-grid"><div><a class="brand" href="index.html"><img src="assets/logo-nova.jpg" alt="" width="48" height="48"><span>OUTLET <small>DO MAICÃO</small></span></a><p>O sofá para sua casa está aqui.</p></div><div><strong>Explore</strong><a href="saldao.html">Saldão</a><a href="comfort.html">Comfort</a><a href="premium.html">Premium</a></div><div><strong>Conecte-se</strong><a href="https://www.instagram.com/outlet.domaicao_02/" target="_blank" rel="noopener">Instagram</a><a href="https://www.facebook.com/profile.php?id=61588798613067&amp;locale=pt_BR" target="_blank" rel="noopener">Facebook</a><a href="https://wa.me/5519996524100" target="_blank" rel="noopener">WhatsApp</a></div><div><strong>Loja 02</strong><a href="{MAP}" target="_blank" rel="noopener">Endereço e horário no Google</a><a href="tel:+5519996524100">(19) 99652-4100</a></div></div><div class="container footer-bottom">© 2026 Outlet do Maicão · Imagens meramente ilustrativas. Modelos e condições sujeitos à confirmação na loja.</div></footer><a class="floating-cta" href="{zap('Olá! Vim pelo site e quero ajuda para escolher um sofá.')}" target="_blank" rel="noopener" aria-label="Falar no WhatsApp"><svg class="whatsapp-icon" viewBox="0 0 24 24" aria-hidden="true" fill="currentColor"><path d="M20.52 3.48A11.85 11.85 0 0 0 12.05 0C5.47 0 .12 5.35.12 11.93c0 2.1.55 4.15 1.6 5.96L.02 24l6.25-1.64a11.93 11.93 0 0 0 5.77 1.47h.01c6.58 0 11.93-5.35 11.93-11.93 0-3.19-1.24-6.18-3.46-8.42ZM12.05 21.8a9.9 9.9 0 0 1-5.04-1.38l-.36-.21-3.71.97.99-3.62-.23-.37a9.9 9.9 0 1 1 8.35 4.61Zm5.43-7.42c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.65.07-.3-.15-1.26-.46-2.41-1.49-.89-.79-1.5-1.77-1.67-2.07-.17-.3-.02-.46.13-.61.13-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.08-.15-.67-1.62-.92-2.21-.24-.58-.48-.5-.67-.51h-.57c-.2 0-.52.07-.8.37-.27.3-1.04 1.02-1.04 2.49s1.07 2.89 1.21 3.09c.15.2 2.1 3.2 5.1 4.49.71.31 1.27.49 1.7.62.71.23 1.36.2 1.87.12.57-.09 1.76-.72 2.01-1.42.25-.7.25-1.29.17-1.42-.07-.12-.27-.2-.57-.35Z"/></svg></a>'''
def layout(title,description,current,body):
    return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102c6b"><meta name="description" content="{escape(description,quote=True)}"><title>{escape(title)}</title><link rel="icon" href="assets/logo-nova.jpg"><link rel="stylesheet" href="styles.css"><meta property="og:type" content="website"><meta property="og:title" content="{escape(title,quote=True)}"><meta property="og:description" content="{escape(description,quote=True)}"><meta property="og:image" content="https://outlet-do-maicao-2.vercel.app/assets/logo-nova.jpg"><script defer src="assets/meta-tracking.js"></script></head><body><noscript><img height="1" width="1" style="display:none" alt="" src="https://www.facebook.com/tr?id=1832634061075614&amp;ev=PageView&amp;noscript=1"></noscript>{header(current)}<main>{body}</main>{footer()}</body></html>'''

def lines(exclude=None):
    cards=[('Saldão','saldao.html','01 / OPORTUNIDADES','Peças rotativas com pequenos detalhes, para conferir de perto.','linha-saldao.webp','sale'),('Comfort','comfort.html','02 / DIA A DIA','Uma ótima combinação de conforto e qualidade para a rotina.','linha-comfort.webp','comfort'),('Premium','premium.html','03 / MAIS REQUINTE','Materiais, acabamento e detalhes para uma experiência superior.','linha-premium-v2.webp','premium')]
    cards=[x for x in cards if x[0]!=exclude]
    return '<div class="line-grid '+('two' if exclude else '')+'">'+''.join(f'<a class="line-card {tone}" href="{url}"><span class="line-no">{num}</span><div class="card-art"><img src="assets/{img}" alt="Sofá da linha {name} reimaginado em ambiente claro" loading="lazy"></div><h3>{name}</h3><p>{desc}</p><span class="card-link">Conhecer a linha </span></a>' for name,url,num,desc,img,tone in cards)+'</div><p class="image-caption">Imagens meramente ilustrativas. Consulte modelos, características e disponibilidade com a loja.</p>'
def process():
    items=[('01','Conte o que procura','Compartilhe medida, cor, estilo e a linha que chamou sua atenção.'),('02','Veja as opções','Enviamos modelos disponíveis e ajudamos a escolher.'),('03','Venha experimentar','Conheça os detalhes e o conforto pessoalmente.'),('04','Combine a entrega','Depois da compra, alinhamos o agendamento e o acesso ao local.')]
    return '<section class="section steps" id="como-funciona"><div class="container"><div class="section-head"><div><span class="eyebrow">DO PRIMEIRO CONTATO À SUA SALA</span><h2>Escolher seu sofá pode ser simples.</h2></div><p>A equipe acompanha sua escolha e combina os próximos passos com você.</p></div><ol class="step-grid">'+''.join(f'<li><span>{n}</span><h3>{t}</h3><p>{d}</p></li>' for n,t,d in items)+'</ol></div></section>'
def delivery():
    return f'''<section class="section delivery" id="entrega"><div class="container delivery-grid"><div><span class="eyebrow light">ENTREGA SEM SURPRESAS</span><h2>Da loja para sua casa.</h2><p>Informe seu endereço e o acesso ao imóvel para combinar as condições antes da compra.</p>{button('Consultar entrega',zap('Olá! Quero consultar a entrega de um sofá. Meu bairro é: '),'white')}</div><div class="delivery-box"><div><strong>R$ 100</strong><span>Entrega em Campinas</span></div><div><strong>R$ 10</strong><span>Adicional por escadaria a subir, pago diretamente ao entregador</span></div><div><strong>Outras cidades</strong><span>Consulte o valor com a equipe</span></div><small>Informe endereço, acesso e quantidade de escadarias para confirmar as condições da entrega.</small></div></div></section>'''
def reviews():
    excerpts=[
        ('Thais Godinho','Sofá maravilhoso, compra e entrega super rápida. Atendentes atenciosos, preço maravilhoso.'),
        ('Cleide Leandro','Atendimento excelente, entregadores educados e atenciosos. Nota 1000.'),
        ('Felipe Luiz','Fui muito bem atendido. O atendimento foi excelente, a compra foi tranquila e o preço, muito justo.'),
        ('Debora Santos','O sofá é lindo, super confortável e dá pra perceber a qualidade assim que a gente senta.'),
        ('Edwin Medeiros','Fui bem atendido com minha família, com preços acessíveis. Super recomendo.'),
        ('Isabel Marques','Eu amei a experiência em comprar o meu sofá aqui. Entrega super rápida, consegui tirar todas as minhas dúvidas.'),
        ('Ariadinys Pimentel','Ótima loja, equipe super atenciosa. Precisava da entrega no mesmo dia e ele conseguiu alguém para entregar e montar.'),
        ('Murillo Ferreira','Ótimo atendimento, entrega rápida. Estão de parabéns.'),
        ('Deny Almeida','Produto de primeira, atendimento excelente. Satisfação total.'),
        ('Karen Katiúscia','O melhor atendimento da cidade, e excelente qualidade!'),
        ('Michael Oliveira','Simplesmente fantástico o atendimento e preços.'),
        ('Brenda Vithienes Molina Fornazari','Sofá de muita qualidade, atendimento ótimo e extremamente paciente. Recomendo!')
    ]
    cards=''.join(f'<article class="review-card"><div class="review-card-top"><span class="review-avatar" aria-hidden="true">{escape(name[0])}</span><div><strong>{escape(name)}</strong><small>Avaliação no Google</small></div><span class="review-google" aria-label="Google">G</span></div><div class="review-stars" aria-label="5 estrelas">★★★★★</div><p>“{escape(excerpt)}”</p></article>' for name,excerpt in excerpts)
    return f'''<section class="section reviews" id="avaliacoes"><div class="container"><div class="section-head reviews-head"><div><span class="eyebrow">QUEM COMPROU, CONTA</span><h2>A experiência de quem já escolheu.</h2></div><div><p>5,0 estrelas em 190 avaliações no Google, consultado em 29/09/2026. Trechos selecionados e editados para leitura.</p>{button('Ver avaliações no Google',REVIEWS)}</div></div></div><div class="review-viewport" aria-label="Depoimentos de clientes"><div class="review-track"><div class="review-set">{cards}</div><div class="review-set" aria-hidden="true">{cards}</div></div></div><div class="container"><p class="review-source">Fonte: avaliações públicas do perfil Outlet do Maicão estofados no Google Maps. Arraste para ler no seu ritmo.</p></div></section>'''
def visit():
    return f'''<section class="section visit" id="visite"><div class="container visit-grid"><div><span class="eyebrow">VENHA CONHECER</span><h2>Seu sofá pode estar esperando na loja.</h2><p>Rua Oswaldo Oscar Barthelson, 1249, Jardim Londres, Campinas, SP. Confira o horário atualizado antes de vir.</p><div class="actions">{button('Traçar rota no Google Maps',MAP)}<a class="text-link" href="tel:+5519996524100">Ligar: (19) 99652-4100</a></div></div><div class="map-frame"><iframe title="Mapa do Google: Outlet do Maicão, Jardim Londres, Campinas" src="{MAP_EMBED}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><a href="{MAP}" target="_blank" rel="noopener">Abrir rota no Google Maps</a></div></div></section>'''
def faq():
    qs=[('O que é a linha Saldão?','São oportunidades de peças com pequenos detalhes e alta rotatividade. Consulte a equipe sobre a condição da peça específica antes de comprar.'),('Posso experimentar os sofás na loja?','Sim. A visita ajuda a conferir conforto, acabamento e medidas. Consulte o horário atualizado no Google.'),('Os modelos mostrados estão sempre disponíveis?','Não necessariamente. Eles exemplificam as linhas; peças, cores e medidas podem mudar. Confirme pelo WhatsApp.'),('Como funciona a entrega?','Em Campinas, a entrega custa R$ 100. Há adicional de R$ 10 por escadaria a subir, pago diretamente ao entregador. Para outras cidades, consulte a equipe.'),('Quais são as formas de pagamento?','A loja atende por cartão ou Pix. Confira as condições válidas para o modelo escolhido com a equipe.')]
    return '<section class="section faq" id="duvidas"><div class="container faq-grid"><div><span class="eyebrow">DÚVIDAS FREQUENTES</span><h2>Antes de escolher, vale saber.</h2><p>Se sua dúvida não estiver aqui, a equipe responde pelo WhatsApp.</p></div><div class="faq-list">'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in qs)+'</div></div></section>'
def final_cta(line=None):
    msg='Olá! Vim pelo site. Procuro um sofá com estas características: tamanho, cor e linha de interesse: '
    if line: msg=f'Olá! Vim pela página {line} e quero conhecer as opções. Tamanho e cor que procuro: '
    return f'''<section class="final-cta"><div class="container final-inner"><div><span class="eyebrow light">VAMOS ENCONTRAR O SEU?</span><h2>Conte como você imagina seu sofá.</h2><p>Medida, cor e linha preferida já são um ótimo começo.</p></div>{button('Enviar mensagem',zap(msg),'white')}</div></section>'''

home=f'''<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow light">OUTLET DO MAICÃO · LOJA 02</span><h1>Seu próximo sofá começa com uma <em>boa escolha.</em></h1><p>Encontre a linha que combina com sua casa, seu jeito de usar e o que você procura investir. Nossa equipe ajuda você a escolher e experimentar na loja.</p><div class="actions">{button('Conhecer as linhas','#linhas','white')}<a class="text-link light-link" href="{zap('Olá! Vim pelo site e quero ajuda para escolher um sofá.')}" target="_blank" rel="noopener">Conversar no WhatsApp </a></div><div class="hero-note"><span class="note-dot"></span> Peças rotativas e diferentes opções para conhecer de perto</div></div><div class="hero-art"><div class="hero-art-label">UM SOFÁ PARA <strong>CADA MOMENTO.</strong></div><img src="assets/sofa-hero.svg" alt="Ilustração de sofá azul em uma sala" width="760" height="570"><span class="illustrative">Imagem meramente ilustrativa</span></div></div></section><section class="section intro"><div class="container intro-grid"><div><span class="eyebrow">PRAZER, OUTLET DO MAICÃO</span><h2>O sofá para sua casa está aqui.</h2></div><div><p>Somos uma loja de sofás em Campinas com opções para diferentes necessidades: oportunidades de Saldão, conforto para a rotina e modelos de linha Premium.</p><p>A escolha não precisa acontecer só por uma foto. Conte o tamanho, a cor e o estilo que procura; mostramos opções e recebemos você para conhecer os modelos pessoalmente.</p><a class="text-link" href="#como-funciona">Veja como funciona </a></div></div></section><section class="section lines" id="linhas"><div class="container"><div class="section-head"><div><span class="eyebrow">ESCOLHA SEU CAMINHO</span><h2>Três linhas. Um sofá que faz sentido para você.</h2></div><p>Conheça a proposta de cada linha. A disponibilidade dos modelos pode variar.</p></div>{lines()}</div></section>'''+process()+delivery()+reviews()+visit()+faq()+final_cta()
home=home.replace('<div class="hero-art"><div class="hero-art-label">UM SOFÁ', '<div class="hero-art photo-art"><div class="hero-art-label">UM SOFÁ')
home=home.replace('src="assets/sofa-hero.svg" alt="Ilustração de sofá azul em uma sala" width="760" height="570"', 'src="assets/sofas-hero-reimaginados.webp" alt="Três sofás em ambiente claro, representando diferentes estilos disponíveis no Outlet do Maicão" width="1536" height="1024"')
(ROOT/'index.html').write_text(layout('Outlet do Maicão | O sofá para sua casa está aqui','Conheça o Outlet do Maicão em Campinas: sofás de Saldão, Comfort e Premium. Visite a loja e fale com a equipe pelo WhatsApp.','Início',home),encoding='utf-8')

pages={
 'saldao':dict(name='Saldão',eyebrow='OPORTUNIDADES QUE GIRAM',headline='Boas oportunidades para quem gosta de escolher de perto.',lead='A linha Saldão reúne peças rotativas com pequenos detalhes. Cada sofá tem sua própria condição: vale ver, experimentar e entender exatamente o que você está levando.',art='linha-saldao.webp',models=['Santorini','Liverpool','X Flex'],proposition='O que faz uma peça de Saldão?',points=[('Peças com pequenos detalhes','A equipe mostra os detalhes da peça disponível para você avaliar antes da compra.'),('Alta rotatividade','Modelos e cores mudam com frequência. Vale consultar o que há na loja hoje.'),('Escolha presencial','Confira medidas, conforto e condição da peça pessoalmente.')],note='Os nomes abaixo são exemplos de modelos que podem aparecer na linha. Não representam estoque atual.'),
 'comfort':dict(name='Comfort',eyebrow='CONFORTO PARA TODO DIA',headline='A sala convida. O conforto faz você ficar.',lead='A linha Comfort reúne opções de ótima qualidade para quem quer uma sala acolhedora e um sofá para aproveitar a rotina.',art='linha-comfort.webp',models=['Bugatti','Big'],proposition='Por que conhecer a linha Comfort?',points=[('Para a rotina','Uma escolha pensada para sentar, relaxar e receber bem.'),('Compare pessoalmente','Experimente os assentos e veja medidas, tecidos e acabamentos disponíveis.'),('Ajuda na escolha','Conte o espaço que você tem e o que valoriza em um sofá.')],note='Bugatti e Big são referências da linha. Confirme características e disponibilidade com a equipe.'),
 'premium':dict(name='Premium',eyebrow='DETALHES QUE FAZEM DIFERENÇA',headline='Um sofá para quem quer ir além no conforto e no acabamento.',lead='A linha Premium reúne os modelos de maior destaque da loja, com atenção aos materiais, ao acabamento e à experiência de uso.',art='linha-premium-v2.webp',models=['Luka','Yasmin','Búzios'],proposition='O que esperar da linha Premium?',points=[('Acabamento em destaque','Conheça de perto os detalhes e materiais de cada modelo.'),('Conforto para experimentar','Compare a sensação dos assentos e encostos na loja.'),('Escolha para seu espaço','A equipe ajuda a conferir dimensões, tecido, cor e opções disponíveis.')],note='Luka, Yasmin e Búzios são exemplos da linha. Características e disponibilidade variam por modelo.')}
for slug,d in pages.items():
    name=d['name']; pts=''.join(f'<div><span>✦</span><h3>{t}</h3><p>{p}</p></div>' for t,p in d['points']); models=''.join(f'<span>{m}</span>' for m in d['models'])
    body=f'''<section class="hero line-hero line-hero-compact {slug}"><div class="container hero-grid"><div class="hero-copy"><a class="back-link" href="index.html#linhas">Todas as linhas</a><span class="eyebrow light">LINHA {name.upper()} · {d['eyebrow']}</span><h1>{d['headline']}</h1><p>{d['lead']}</p><div class="actions">{button('Conhecer opções no WhatsApp',zap(f'Olá! Vim pela página {name} e quero conhecer as opções disponíveis. Procuro tamanho e cor: '),'white')}<a class="text-link light-link" href="#sobre">Entenda a linha</a></div></div><div class="hero-art photo-art"><img src="assets/{d['art']}" alt="Sofá da linha {name} reimaginado em uma sala clara" width="1536" height="1024"><span class="illustrative">Imagem meramente ilustrativa</span></div></div></section><section class="section line-about compact-about" id="sobre"><div class="container"><span class="eyebrow">CONHEÇA A PROPOSTA</span><h2>{d['proposition']}</h2><div class="feature-grid">{pts}</div><p>{d['note']}</p><div class="model-tags">{models}</div>{button('Perguntar pelos modelos',zap(f'Olá! Quero saber quais modelos da linha {name} estão disponíveis agora.'))}</div></section>'''+reviews()+delivery()+final_cta(name)
    (ROOT/f'{slug}.html').write_text(layout(f'Linha {name} | Outlet do Maicão',f'Conheça a linha {name} do Outlet do Maicão em Campinas. Veja a proposta, visite a Loja 02 e consulte as opções disponíveis pelo WhatsApp.',name,body),encoding='utf-8')
